name: 'Create child issues'
description: 'Create child issues using labels'
inputs:
  label:
    description: 'The label that triggers the event'
    required: true
  repos:
    description: 'A comma-separated list of owner/name repositories to create the child issues'
    required: true
  add-labels:
    description: 'Optional labels to add to the new child issues'
    required: false
    default: ''
  github_token:
    description: 'Token to use for authenticated GitHub API requests'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
