name: 'Create child issues'
description: 'Create child issues using labels'
inputs:
  repos:
    description: 'A comma-separated list of owner/name repositories to create the child issues'
    required: true
  add-labels:
    description: 'Optional comma-separated labels to add to the new child issues'
    required: false
    default: ''
  child-prefix:
    description: 'A string to prefix to each child issue'
    required: true
    default: '[child] '
  github_token:
    description: 'Token to use for authenticated GitHub API requests'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
